module.exports = {
  status: {
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
  },
  step: {
    INITIALIZE: 'INITIALIZE',
    VERIFICATION: 'VERIFICATION',
    DETAILS_REGISTER: 'DETAILS_REGISTER',
    BROKER_REGISTER: 'BROKER_REGISTER',
    SUBMITTED: 'SUBMITTED',
    COMPLETED: 'COMPLETED',
  },
  stages: {
    SUBMITTED: 'Submitted',
    COMPLETED: 'Completed',
  },
};
